/**
 * Real formula seed data from customer formulation sheets.
 * 6 product formulas: Cerapure Blue/Pink/Iris/Kid, ชาวเขา, นางไพล
 *
 * Stock card IDs for shared ingredients that ARE in the database:
 *   RM009 = เบสใส spaandsoap (Soap Base Clear)
 *   RM010 = ALS (Ammonium Lauryl Sulfate)
 *   RM011 = SLS (Sodium Lauryl Sulfate)
 *   RM012 = Sorbitol
 *   RM013 = BHA
 *   RM014 = Phenoxyethanol
 * Special ingredients (fragrances, dyes, coffee, turmeric) are stored by
 * name+supplier+% only — stockCardId = null until added to inventory.
 */

export const NEW_STOCK_CARDS = [
  {
    id: "RM009",
    itemCode: "RM-201",
    itemName: "เบสใส spaandsoap",
    itemNameEn: "Soap Base Clear (SpaAndSoap)",
    itemType: "raw_material",
    category: "Base",
    unit: "kg",
    balance: 500,
    reservedStock: 0,
    incomingStock: 0,
    available: 500,
    initialStock: 500,
    minStock: 50,
    maxStock: 1000,
    reorderPoint: 100,
    unitCost: 55,
    supplier: "SpaAndSoap",
    location: "RM-A1",
    inventoryStatus: "healthy",
  },
  {
    id: "RM010",
    itemCode: "RM-202",
    itemName: "ALS (Ammonium Lauryl Sulfate)",
    itemNameEn: "ALS - Ammonium Lauryl Sulfate",
    itemType: "raw_material",
    category: "Surfactant",
    unit: "kg",
    balance: 80,
    reservedStock: 0,
    incomingStock: 0,
    available: 80,
    initialStock: 80,
    minStock: 10,
    maxStock: 200,
    reorderPoint: 20,
    unitCost: 120,
    supplier: "บางบัวทองเคมีภัณฑ์",
    location: "RM-B1",
    inventoryStatus: "healthy",
  },
  {
    id: "RM011",
    itemCode: "RM-203",
    itemName: "SLS (Sodium Lauryl Sulfate)",
    itemNameEn: "SLS - Sodium Lauryl Sulfate",
    itemType: "raw_material",
    category: "Surfactant",
    unit: "kg",
    balance: 100,
    reservedStock: 0,
    incomingStock: 0,
    available: 100,
    initialStock: 100,
    minStock: 15,
    maxStock: 250,
    reorderPoint: 30,
    unitCost: 90,
    supplier: "บางบัวทองเคมีภัณฑ์",
    location: "RM-B2",
    inventoryStatus: "healthy",
  },
  {
    id: "RM012",
    itemCode: "RM-204",
    itemName: "Sorbitol 70%",
    itemNameEn: "Sorbitol 70%",
    itemType: "raw_material",
    category: "Humectant",
    unit: "kg",
    balance: 60,
    reservedStock: 0,
    incomingStock: 0,
    available: 60,
    initialStock: 60,
    minStock: 10,
    maxStock: 150,
    reorderPoint: 20,
    unitCost: 75,
    supplier: "บางบัวทองเคมีภัณฑ์",
    location: "RM-C1",
    inventoryStatus: "healthy",
  },
  {
    id: "RM013",
    itemCode: "RM-205",
    itemName: "BHA (Salicylic Acid / BHA)",
    itemNameEn: "BHA - Butylated Hydroxyanisole",
    itemType: "raw_material",
    category: "Preservative",
    unit: "kg",
    balance: 5,
    reservedStock: 0,
    incomingStock: 0,
    available: 5,
    initialStock: 5,
    minStock: 1,
    maxStock: 20,
    reorderPoint: 2,
    unitCost: 850,
    supplier: "กรุงเทพเคมี",
    location: "RM-D1",
    inventoryStatus: "low",
  },
  {
    id: "RM014",
    itemCode: "RM-206",
    itemName: "Phenoxyethanol",
    itemNameEn: "Phenoxyethanol",
    itemType: "raw_material",
    category: "Preservative",
    unit: "kg",
    balance: 10,
    reservedStock: 0,
    incomingStock: 0,
    available: 10,
    initialStock: 10,
    minStock: 2,
    maxStock: 30,
    reorderPoint: 4,
    unitCost: 680,
    supplier: "THE REAL THREE",
    location: "RM-D2",
    inventoryStatus: "healthy",
  },
]

// ---------------------------------------------------------------------------
// Formulas
// ---------------------------------------------------------------------------
export const FORMULA_ROWS = [
  {
    id: "F-001",
    code: "CPB-001",
    name: "Cerapure Blue",
    nameEn: "Cerapure Blue Body Wash",
    category: "body_wash",
    base: "เบสใส spaandsoap",
    batchSizeKg: 10,
    yield: 100,
    status: "active",
    version: "1.0",
    notes: "สูตรครีมอาบน้ำสีฟ้า กลิ่น Protex Blossom",
  },
  {
    id: "F-002",
    code: "CPP-001",
    name: "Cerapure Pink",
    nameEn: "Cerapure Pink Body Wash",
    category: "body_wash",
    base: "เบสใส spaandsoap",
    batchSizeKg: 10,
    yield: 100,
    status: "active",
    version: "1.0",
    notes: "สูตรครีมอาบน้ำสีชมพู กลิ่น Sweet",
  },
  {
    id: "F-003",
    code: "CPI-001",
    name: "Cerapure Iris",
    nameEn: "Cerapure Iris Body Wash",
    category: "body_wash",
    base: "เบสใส spaandsoap",
    batchSizeKg: 10,
    yield: 100,
    status: "active",
    version: "1.0",
    notes: "สูตรครีมอาบน้ำสีม่วง กลิ่น Omnia บัวหลวง",
  },
  {
    id: "F-004",
    code: "CPK-001",
    name: "Cerapure Kid",
    nameEn: "Cerapure Kid Body Wash",
    category: "body_wash",
    base: "เบสใส spaandsoap",
    batchSizeKg: 10,
    yield: 100,
    status: "active",
    version: "1.0",
    notes: "สูตรครีมอาบน้ำสำหรับเด็ก กลิ่น VIOLET BABI",
  },
  {
    id: "F-005",
    code: "CKH-001",
    name: "ชาวเขา",
    nameEn: "Chao Khao Herbal Body Wash",
    category: "body_wash",
    base: "เบสใส spaandsoap",
    batchSizeKg: 10,
    yield: 100,
    status: "active",
    version: "1.0",
    notes: "สูตรสมุนไพร ผงกาแฟ ขมิ้น กลิ่นกาแฟ",
  },
  {
    id: "F-006",
    code: "NPI-001",
    name: "นางไพล",
    nameEn: "Nang Phai Herbal Body Wash",
    category: "body_wash",
    base: "เบสใส spaandsoap",
    batchSizeKg: 10,
    yield: 100,
    status: "active",
    version: "1.0",
    notes: "สูตรสมุนไพรไพล ผงกาแฟ กลิ่นฟรุ๊ตเมล่อน สีเขียว",
  },
]

// ---------------------------------------------------------------------------
// Ingredients  (percentage values are as-given in the formulation sheet)
// base % = 100 - sum(all other ingredients)
// ---------------------------------------------------------------------------
export const INGREDIENT_ROWS = [
  // ── F-001 Cerapure Blue ─────────────────────────────────────────────────
  { id: "FI-001-01", formulaId: "F-001", sortOrder: 1, rawMaterialName: "เบสใส spaandsoap", supplier: "SpaAndSoap",               percentage: 95.455, stockCardId: "RM009", unit: "kg" },
  { id: "FI-001-02", formulaId: "F-001", sortOrder: 2, rawMaterialName: "ALS",              supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 1,      stockCardId: "RM010", unit: "kg" },
  { id: "FI-001-03", formulaId: "F-001", sortOrder: 3, rawMaterialName: "SLS",              supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 1,      stockCardId: "RM011", unit: "kg" },
  { id: "FI-001-04", formulaId: "F-001", sortOrder: 4, rawMaterialName: "Sorbitol",         supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 1,      stockCardId: "RM012", unit: "kg" },
  { id: "FI-001-05", formulaId: "F-001", sortOrder: 5, rawMaterialName: "Protex Blossom",   supplier: "Fragrantika",               percentage: 1.5,    stockCardId: null,    unit: "kg", notes: "กลิ่น Protex Blossom" },
  { id: "FI-001-06", formulaId: "F-001", sortOrder: 6, rawMaterialName: "สีฟ้า (2:100)",   supplier: "อดินพ",                     percentage: 0.045,  stockCardId: null,    unit: "g",  notes: "เจือจาง 2:100" },

  // ── F-002 Cerapure Pink ─────────────────────────────────────────────────
  { id: "FI-002-01", formulaId: "F-002", sortOrder: 1, rawMaterialName: "เบสใส spaandsoap", supplier: "SpaAndSoap",               percentage: 94.938, stockCardId: "RM009", unit: "kg" },
  { id: "FI-002-02", formulaId: "F-002", sortOrder: 2, rawMaterialName: "ALS",              supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 0.5,    stockCardId: "RM010", unit: "kg" },
  { id: "FI-002-03", formulaId: "F-002", sortOrder: 3, rawMaterialName: "SLS",              supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 1,      stockCardId: "RM011", unit: "kg" },
  { id: "FI-002-04", formulaId: "F-002", sortOrder: 4, rawMaterialName: "Sorbitol",         supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 1,      stockCardId: "RM012", unit: "kg" },
  { id: "FI-002-05", formulaId: "F-002", sortOrder: 5, rawMaterialName: "Sweet เก่า",       supplier: "TCFF",                      percentage: 1,      stockCardId: null,    unit: "kg" },
  { id: "FI-002-06", formulaId: "F-002", sortOrder: 6, rawMaterialName: "Sweet ใหม่",       supplier: "TCFF",                      percentage: 1.5,    stockCardId: null,    unit: "kg" },
  { id: "FI-002-07", formulaId: "F-002", sortOrder: 7, rawMaterialName: "สีชมพูCI (5:100)", supplier: "mildsoap",                  percentage: 0.057,  stockCardId: null,    unit: "g",  notes: "เจือจาง 5:100" },
  { id: "FI-002-08", formulaId: "F-002", sortOrder: 8, rawMaterialName: "สีชมพู (2:100)",   supplier: "อดินพ",                     percentage: 0.0046, stockCardId: null,    unit: "g",  notes: "เจือจาง 2:100" },

  // ── F-003 Cerapure Iris ─────────────────────────────────────────────────
  { id: "FI-003-01", formulaId: "F-003", sortOrder: 1, rawMaterialName: "เบสใส spaandsoap", supplier: "SpaAndSoap",               percentage: 95.35,  stockCardId: "RM009", unit: "kg" },
  { id: "FI-003-02", formulaId: "F-003", sortOrder: 2, rawMaterialName: "ALS",              supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 0.5,    stockCardId: "RM010", unit: "kg" },
  { id: "FI-003-03", formulaId: "F-003", sortOrder: 3, rawMaterialName: "SLS",              supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 1,      stockCardId: "RM011", unit: "kg" },
  { id: "FI-003-04", formulaId: "F-003", sortOrder: 4, rawMaterialName: "Sorbitol",         supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 1,      stockCardId: "RM012", unit: "kg" },
  { id: "FI-003-05", formulaId: "F-003", sortOrder: 5, rawMaterialName: "กลิ่น Omnia",      supplier: "บัวหลวง",                   percentage: 2,      stockCardId: null,    unit: "kg" },
  { id: "FI-003-06", formulaId: "F-003", sortOrder: 6, rawMaterialName: "สีม่วง",           supplier: "chemical max",              percentage: 0.15,   stockCardId: null,    unit: "g" },
  { id: "FI-003-07", formulaId: "F-003", sortOrder: 7, rawMaterialName: "สีชมพู (2:100)",   supplier: "อดินพ",                     percentage: 0.00027,stockCardId: null,    unit: "g",  notes: "เจือจาง 2:100" },

  // ── F-004 Cerapure Kid ──────────────────────────────────────────────────
  { id: "FI-004-01", formulaId: "F-004", sortOrder: 1, rawMaterialName: "เบสใส spaandsoap", supplier: "SpaAndSoap",               percentage: 96.959, stockCardId: "RM009", unit: "kg" },
  { id: "FI-004-02", formulaId: "F-004", sortOrder: 2, rawMaterialName: "Sorbitol",         supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 1,      stockCardId: "RM012", unit: "kg" },
  { id: "FI-004-03", formulaId: "F-004", sortOrder: 3, rawMaterialName: "VIOLET BABI",      supplier: "TCFF",                      percentage: 2,      stockCardId: null,    unit: "kg", notes: "กลิ่นเด็ก" },
  { id: "FI-004-04", formulaId: "F-004", sortOrder: 4, rawMaterialName: "สีเหลือง Sweet",   supplier: "karaboon",                  percentage: 0.019,  stockCardId: null,    unit: "g" },
  { id: "FI-004-05", formulaId: "F-004", sortOrder: 5, rawMaterialName: "สีส้ม (5:100)",    supplier: "mildsoap",                  percentage: 0.022,  stockCardId: null,    unit: "g",  notes: "เจือจาง 5:100" },

  // ── F-005 ชาวเขา ────────────────────────────────────────────────────────
  { id: "FI-005-01", formulaId: "F-005", sortOrder: 1, rawMaterialName: "เบสใส spaandsoap", supplier: "SpaAndSoap",               percentage: 88.55,  stockCardId: "RM009", unit: "kg" },
  { id: "FI-005-02", formulaId: "F-005", sortOrder: 2, rawMaterialName: "BHA",              supplier: "กรุงเทพเคมี",               percentage: 0.22,   stockCardId: "RM013", unit: "kg" },
  { id: "FI-005-03", formulaId: "F-005", sortOrder: 3, rawMaterialName: "Alcohol",          supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 0.18,   stockCardId: null,    unit: "kg" },
  { id: "FI-005-04", formulaId: "F-005", sortOrder: 4, rawMaterialName: "น้ำหอมกาแฟ",      supplier: "IMPRESS",                   percentage: 0.8,    stockCardId: null,    unit: "kg" },
  { id: "FI-005-05", formulaId: "F-005", sortOrder: 5, rawMaterialName: "ผงกาแฟ",          supplier: "บ้านแพ้ว",                  percentage: 10,     stockCardId: null,    unit: "kg" },
  { id: "FI-005-06", formulaId: "F-005", sortOrder: 6, rawMaterialName: "ขมิ้น",           supplier: "ดีดี ไทยโอสถ",              percentage: 0.05,   stockCardId: null,    unit: "kg" },
  { id: "FI-005-07", formulaId: "F-005", sortOrder: 7, rawMaterialName: "Phenoxyethanol",   supplier: "THE REAL THREE",            percentage: 0.2,    stockCardId: "RM014", unit: "kg" },

  // ── F-006 นางไพล ────────────────────────────────────────────────────────
  { id: "FI-006-01", formulaId: "F-006", sortOrder: 1, rawMaterialName: "เบสใส spaandsoap", supplier: "SpaAndSoap",               percentage: 74.96,  stockCardId: "RM009", unit: "kg" },
  { id: "FI-006-02", formulaId: "F-006", sortOrder: 2, rawMaterialName: "BHA",              supplier: "กรุงเทพเคมี",               percentage: 0.22,   stockCardId: "RM013", unit: "kg" },
  { id: "FI-006-03", formulaId: "F-006", sortOrder: 3, rawMaterialName: "PG",               supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 0.44,   stockCardId: null,    unit: "kg", notes: "Propylene Glycol" },
  { id: "FI-006-04", formulaId: "F-006", sortOrder: 4, rawMaterialName: "Alcohol",          supplier: "บางบัวทองเคมีภัณฑ์",       percentage: 0.18,   stockCardId: null,    unit: "kg" },
  { id: "FI-006-05", formulaId: "F-006", sortOrder: 5, rawMaterialName: "ฟรุ๊ตเมล่อน",     supplier: "ฮงฮวด",                     percentage: 1,      stockCardId: null,    unit: "kg" },
  { id: "FI-006-06", formulaId: "F-006", sortOrder: 6, rawMaterialName: "ผงกาแฟ",          supplier: "บ้านแพ้ว",                  percentage: 10,     stockCardId: null,    unit: "kg" },
  { id: "FI-006-07", formulaId: "F-006", sortOrder: 7, rawMaterialName: "Phenoxyethanol",   supplier: "THE REAL THREE",            percentage: 0.2,    stockCardId: "RM014", unit: "kg" },
  { id: "FI-006-08", formulaId: "F-006", sortOrder: 8, rawMaterialName: "สีเขียว973 (5:100)", supplier: "ไทยสงวนวัฒน์เคมีภัณฑ์", percentage: 3,      stockCardId: null,    unit: "g",  notes: "เจือจาง 5:100" },
  { id: "FI-006-09", formulaId: "F-006", sortOrder: 9, rawMaterialName: "สีเขียวแอปเปิ้ล (5:100)", supplier: "ไทยสงวนวัฒน์เคมีภัณฑ์", percentage: 10, stockCardId: null, unit: "g",  notes: "เจือจาง 5:100" },
]

// ---------------------------------------------------------------------------
// Initial Job Orders (5 records)
// ---------------------------------------------------------------------------
export const JOB_ORDER_ROWS = [
  {
    id: "JO-001",
    jobNo: "JO-2025-001",
    formulaId: "F-001",
    formulaName: "Cerapure Blue",
    formulaCode: "CPB-001",
    customer: "บริษัท คอสเม่ ดิสทริบิวเตอร์ จำกัด",
    batchSizeKg: 50,
    plannedQty: 500,
    unit: "kg",
    status: "completed",
    priority: "normal",
    plannedStart: "2025-03-01",
    plannedEnd: "2025-03-03",
    actualStart: "2025-03-01",
    actualEnd: "2025-03-03",
    assignedTo: "ทีม A",
    costBreakdown: { rawMaterial: 15000, packaging: 5000, labor: 5000, overhead: 3000, total: 25000 },
  },
  {
    id: "JO-002",
    jobNo: "JO-2025-002",
    formulaId: "F-002",
    formulaName: "Cerapure Pink",
    formulaCode: "CPP-001",
    customer: "ร้าน Beauty Plus",
    batchSizeKg: 30,
    plannedQty: 300,
    unit: "kg",
    status: "completed",
    priority: "normal",
    plannedStart: "2025-03-05",
    plannedEnd: "2025-03-06",
    actualStart: "2025-03-05",
    actualEnd: "2025-03-06",
    assignedTo: "ทีม B",
    costBreakdown: { rawMaterial: 9000, packaging: 3000, labor: 3000, overhead: 1800, total: 15000 },
  },
  {
    id: "JO-003",
    jobNo: "JO-2025-003",
    formulaId: "F-005",
    formulaName: "ชาวเขา",
    formulaCode: "CKH-001",
    customer: "ร้าน Herbal House",
    batchSizeKg: 20,
    plannedQty: 200,
    unit: "kg",
    status: "in_progress",
    priority: "high",
    plannedStart: "2025-07-01",
    plannedEnd: "2025-07-03",
    actualStart: "2025-07-01",
    assignedTo: "ทีม A",
    costBreakdown: { rawMaterial: 6000, packaging: 2000, labor: 2000, overhead: 1200, total: 10000 },
  },
  {
    id: "JO-004",
    jobNo: "JO-2025-004",
    formulaId: "F-006",
    formulaName: "นางไพล",
    formulaCode: "NPI-001",
    customer: "ร้าน Thai Herb Shop",
    batchSizeKg: 20,
    plannedQty: 200,
    unit: "kg",
    status: "pending",
    priority: "normal",
    plannedStart: "2025-07-08",
    plannedEnd: "2025-07-10",
    assignedTo: "ทีม B",
    costBreakdown: { rawMaterial: 6000, packaging: 2000, labor: 2000, overhead: 1200, total: 10000 },
  },
  {
    id: "JO-005",
    jobNo: "JO-2025-005",
    formulaId: "F-004",
    formulaName: "Cerapure Kid",
    formulaCode: "CPK-001",
    customer: "บริษัท คิดส์ เบบี้ จำกัด",
    batchSizeKg: 40,
    plannedQty: 400,
    unit: "kg",
    status: "pending",
    priority: "urgent",
    plannedStart: "2025-07-10",
    plannedEnd: "2025-07-12",
    assignedTo: "ทีม A",
    costBreakdown: { rawMaterial: 12000, packaging: 4000, labor: 4000, overhead: 2400, total: 20000 },
  },
]
