"use client"

import { useState, useMemo } from "react"
import { Truck, Package, Info, CheckCircle2, ArrowDownToLine } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogClose,
} from "@/components/ui/dialog"
import { useStockSimulation } from "@/lib/stock-simulation-context"
import { getStockItem } from "@/lib/stock-simulation-store"

export function StockIncomingTab() {
  const { state, confirmPartialReceive } = useStockSimulation()
  const [receiveModalOpen, setReceiveModalOpen] = useState(false)
  const [currentPOIdx, setCurrentPOIdx] = useState<number | null>(null)
  const [receiveQuantities, setReceiveQuantities] = useState<number[]>([])

  const pending = useMemo(
    () => state.purchaseOrders.filter((p) => p.status === "PENDING" || p.status === "PARTIAL"),
    [state.purchaseOrders]
  )
  const received = useMemo(
    () => state.purchaseOrders.filter((p) => p.status === "RECEIVED").slice(-5).reverse(),
    [state.purchaseOrders]
  )

  function openReceiveModal(poIdx: number) {
    const po = state.purchaseOrders[poIdx]
    if (!po) return
    setCurrentPOIdx(poIdx)
    setReceiveQuantities(
      po.items.map((it) => {
        const remaining = it.qty - (it.receivedQty || 0)
        return remaining > 0 ? remaining : 0
      })
    )
    setReceiveModalOpen(true)
  }

  function handleConfirmReceive() {
    if (currentPOIdx === null) return
    confirmPartialReceive(currentPOIdx, receiveQuantities)
    setReceiveModalOpen(false)
    setCurrentPOIdx(null)
  }

  const currentPO = currentPOIdx !== null ? state.purchaseOrders[currentPOIdx] : null

  return (
    <div className="flex flex-col gap-4">
      {/* Hint */}
      <div className="flex items-start gap-2.5 rounded-2xl bg-[#e0f7f5] p-4 text-[12px] text-teal-800">
        <Truck className="mt-0.5 h-4 w-4 shrink-0" />
        <div>
          <strong className="font-semibold">Receiving Area</strong> -- When you press &quot;Receive&quot;:<br />
          1. Adds to Physical Stock &nbsp; 2. Checks Waiting Jobs &nbsp; 3. Auto-Allocates to Jobs (FIFO)
        </div>
      </div>

      {/* Main Table */}
      <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
        <div className="flex items-center justify-between border-b border-border px-5 py-3">
          <h3 className="text-sm font-bold text-foreground">Pending Purchase Orders</h3>
          <Badge variant="outline" className="rounded-lg border-0 bg-blue-100 px-2.5 py-0.5 text-[10px] font-semibold text-blue-700">
            {pending.length} Pending
          </Badge>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-[13px]">
            <thead>
              <tr className="bg-secondary">
                <th className="px-4 py-3 text-left text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Document No.</th>
                <th className="px-4 py-3 text-left text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Supplier</th>
                <th className="px-4 py-3 text-left text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Items & Progress</th>
                <th className="px-4 py-3 text-left text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Est. Arrival</th>
                <th className="px-4 py-3 text-right text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Action</th>
              </tr>
            </thead>
            <tbody>
              {pending.length === 0 && received.length === 0 ? (
                <tr>
                  <td colSpan={5} className="py-16 text-center text-muted-foreground">No purchase orders</td>
                </tr>
              ) : (
                <>
                  {pending.map((po) => {
                    const realIdx = state.purchaseOrders.indexOf(po)
                    const isPartial = po.status === "PARTIAL"
                    const totalQty = po.items.reduce((s, it) => s + it.qty, 0)
                    const totalReceived = po.items.reduce((s, it) => s + (it.receivedQty || 0), 0)
                    const pct = totalQty > 0 ? Math.round((totalReceived / totalQty) * 100) : 0

                    return (
                      <tr key={po.poNo} className={`border-b border-border ${po.autoGenerated ? "bg-red-50/30" : isPartial ? "bg-blue-50/30" : ""}`}>
                        <td className="px-4 py-3">
                          <span className="rounded-md bg-violet-100 px-2 py-0.5 font-mono text-[11px] font-bold text-violet-700">{po.poNo}</span>
                          {po.autoGenerated && (
                            <div className="mt-1 text-[9px] font-bold text-destructive">Auto-Generated (Shortage)</div>
                          )}
                          {isPartial && (
                            <div className="mt-1 text-[9px] font-bold text-blue-600">Partial Received</div>
                          )}
                          {po.extraNote && (
                            <div className="mt-1 text-[9px] font-semibold text-teal-600">{po.extraNote}</div>
                          )}
                        </td>
                        <td className="px-4 py-3 text-xs">{po.supplier}</td>
                        <td className="px-4 py-3">
                          <div className="flex flex-col gap-1">
                            {po.items.map((it, ii) => {
                              const rcv = it.receivedQty || 0
                              const remaining = it.qty - rcv
                              const si = getStockItem(state.stock, it.itemId)
                              return (
                                <div key={ii}>
                                  <Badge
                                    variant="outline"
                                    className={`rounded-md border-0 px-2 py-0.5 text-[10px] font-semibold ${po.autoGenerated ? "bg-red-100 text-red-700" : rcv > 0 ? "bg-blue-100 text-blue-700" : "bg-teal-100 text-teal-700"}`}
                                  >
                                    {it.name}: {remaining > 0 ? remaining : it.qty} {si?.unit || ""}
                                  </Badge>
                                  {rcv > 0 && (
                                    <span className="ml-1 text-[9px] font-semibold text-emerald-600">(received: {rcv})</span>
                                  )}
                                  {it.extraQty && it.extraQty > 0 && rcv === 0 && (
                                    <div className="mt-0.5 pl-1 text-[9px] text-muted-foreground">
                                      <span className="text-destructive">Shortage: {it.shortageQty || 0}</span> + <span className="text-teal-600">Extra: +{it.extraQty}</span>
                                    </div>
                                  )}
                                </div>
                              )
                            })}
                            {isPartial && (
                              <div className="mt-1 flex items-center gap-2">
                                <div className="h-2 flex-1 overflow-hidden rounded-full bg-secondary">
                                  <div className="h-full rounded-full bg-primary transition-all" style={{ width: `${pct}%` }} />
                                </div>
                                <span className="font-mono text-[10px] font-bold text-primary">{pct}%</span>
                              </div>
                            )}
                          </div>
                        </td>
                        <td className="px-4 py-3 text-xs text-muted-foreground">{po.eta}</td>
                        <td className="px-4 py-3 text-right">
                          <Button
                            size="sm"
                            className="h-8 gap-1 rounded-xl text-[11px]"
                            onClick={() => openReceiveModal(realIdx)}
                          >
                            <ArrowDownToLine className="h-3 w-3" />
                            {isPartial ? "Receive More" : "Receive"}
                          </Button>
                        </td>
                      </tr>
                    )
                  })}

                  {/* Recently received */}
                  {received.map((po) => {
                    const srrRecs = state.receiveRecords.filter((r) => r.sinRef === po.poNo)
                    return (
                      <tr key={po.poNo} className="border-b border-border opacity-60">
                        <td className="px-4 py-3">
                          <span className="font-semibold line-through">{po.poNo}</span>
                          {srrRecs.length > 0 && (
                            <div className="mt-1 flex flex-wrap gap-1">
                              {srrRecs.map((s) => (
                                <span key={s.srrNo} className="rounded-md bg-emerald-100 px-2 py-0.5 font-mono text-[9px] font-bold text-emerald-700">{s.srrNo}</span>
                              ))}
                            </div>
                          )}
                        </td>
                        <td className="px-4 py-3 text-xs">{po.supplier}</td>
                        <td className="px-4 py-3">
                          {po.items.map((it, ii) => {
                            const rcv = it.receivedQty || 0
                            const excess = Math.max(0, rcv - it.qty)
                            return (
                              <Badge key={ii} variant="outline" className="mr-1 rounded-md border-0 bg-teal-100 px-2 py-0.5 text-[10px] font-semibold text-teal-700 opacity-70">
                                {it.name}: {it.qty}{excess > 0 ? ` +${excess}` : ""}
                              </Badge>
                            )
                          })}
                        </td>
                        <td className="px-4 py-3 text-xs text-muted-foreground">{po.eta}</td>
                        <td className="px-4 py-3 text-right">
                          <Badge variant="outline" className="rounded-lg border-0 bg-emerald-100 px-2 py-0.5 text-[10px] font-semibold text-emerald-700">
                            Received
                          </Badge>
                        </td>
                      </tr>
                    )
                  })}
                </>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Receive Modal */}
      <Dialog open={receiveModalOpen} onOpenChange={setReceiveModalOpen}>
        <DialogContent className="max-w-lg rounded-2xl">
          <DialogHeader>
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-100">
                <ArrowDownToLine className="h-5 w-5 text-emerald-600" />
              </div>
              <div>
                <DialogTitle className="text-base font-bold">Receive Stock</DialogTitle>
                <p className="text-[12px] text-muted-foreground">
                  PO: <strong>{currentPO?.poNo}</strong> -- Enter actual quantities received (partial receive allowed, over-receive for bonuses)
                </p>
              </div>
            </div>
          </DialogHeader>

          <div className="max-h-[400px] space-y-3 overflow-y-auto">
            {currentPO?.items.map((it, idx) => {
              const remaining = it.qty - (it.receivedQty || 0)
              const rcvPct = it.qty > 0 ? Math.round(((it.receivedQty || 0) / it.qty) * 100) : 0
              const si = getStockItem(state.stock, it.itemId)
              const currentQty = receiveQuantities[idx] || 0
              const excess = currentQty - remaining

              return (
                <div key={idx} className="flex items-center gap-4 border-b border-border pb-3">
                  <div className="min-w-0 flex-1">
                    <div className="text-[13px] font-semibold">{it.name}</div>
                    <div className="text-[10px] text-muted-foreground">
                      {si?.code || ""} -- Ordered: {it.qty} {si?.unit || ""} -- Received: {it.receivedQty || 0}
                    </div>
                    <div className="mt-1 flex max-w-[200px] items-center gap-2">
                      <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-secondary">
                        <div
                          className={`h-full rounded-full transition-all ${rcvPct >= 100 ? "bg-emerald-500" : "bg-primary"}`}
                          style={{ width: `${Math.min(rcvPct, 100)}%` }}
                        />
                      </div>
                      <span className={`font-mono text-[10px] font-bold ${rcvPct >= 100 ? "text-emerald-600" : "text-primary"}`}>{rcvPct}%</span>
                    </div>
                  </div>
                  <div className="text-center">
                    <div className="mb-1 text-[10px] text-muted-foreground">Receive Qty</div>
                    <Input
                      type="number"
                      value={receiveQuantities[idx] || 0}
                      onChange={(e) => {
                        const newQ = [...receiveQuantities]
                        newQ[idx] = Math.max(0, parseFloat(e.target.value) || 0)
                        setReceiveQuantities(newQ)
                      }}
                      className="h-9 w-[90px] rounded-xl text-center font-mono text-xs font-bold"
                      min={0}
                    />
                    <div className="mt-1 text-[9px]">
                      {currentQty <= 0 ? (
                        <span className="text-muted-foreground">Remaining: {remaining > 0 ? remaining : 0}</span>
                      ) : excess > 0 ? (
                        <span className="font-semibold text-teal-600">Excess +{excess.toLocaleString(undefined, { maximumFractionDigits: 2 })} (bonus)</span>
                      ) : currentQty < remaining ? (
                        <span className="text-blue-600">Partial -- {(remaining - currentQty).toLocaleString(undefined, { maximumFractionDigits: 2 })} remaining</span>
                      ) : (
                        <span className="text-emerald-600">Exact match</span>
                      )}
                    </div>
                  </div>
                </div>
              )
            })}
          </div>

          <DialogFooter>
            <DialogClose asChild><Button variant="ghost" className="rounded-xl text-xs">Cancel</Button></DialogClose>
            <Button
              className="gap-1 rounded-xl bg-emerald-600 text-xs text-white hover:bg-emerald-700"
              onClick={handleConfirmReceive}
              disabled={receiveQuantities.every((q) => q <= 0)}
            >
              <CheckCircle2 className="h-3.5 w-3.5" /> Confirm Receive
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
