import type { JobOrder } from "./job-order-types"

export const mockJobOrders: JobOrder[] = [
  {
    id: "jo-1",
    orderNumber: "CZ-2601",
    customerId: "c-1",
    customerName: "Glow Lab Co., Ltd.",
    brandName: "GlowUp",
    productName: "Vitamin C Brightening Serum 15%",
    sku: "SKU-VC15-30",
    formulaCode: "FM-VC15-R3",
    fdaRegNumber: "10-1-67-00234",
    fdaStatus: "active",
    quantity: 5000,
    unitSize: "30ml",
    batchSize: 2500,
    numberOfBatches: 2,
    status: "in_production",
    priority: "high",
    totalValue: 185000,
    costPerUnit: 28,
    sellingPricePerUnit: 37,
    paymentTerms: "Net 30",
    dueDate: "2026-02-28",
    startDate: "2026-02-14",
    notes: "Customer requires Ethyl Ascorbic Acid from Japanese supplier.\nMust deliver before Feb 28 for 3.3 campaign.",
    createdAt: "2026-02-14",
    updatedAt: "2026-02-21",
    batches: [
      { id: "b-1", batchNumber: "#B-2601A", quantity: 2000, status: "qc_passed", completedDate: "2026-02-18" },
      { id: "b-2", batchNumber: "#B-2601B", quantity: 1200, status: "waiting_qc", completedDate: "2026-02-20" },
      { id: "b-3", batchNumber: "#B-2601C", quantity: 1800, status: "producing", completedDate: null },
    ],
    productionSteps: [
      {
        id: "s-1", stepNumber: 1, name: "Receive Order", description: "Confirm specs, price, MOQ, delivery date",
        status: "done", targetQty: 1, completedQty: 1, goodQty: 1, defectQty: 0, unit: "order",
        startDate: "2026-02-14", endDate: "2026-02-14",
        dailyRecords: [
          { id: "r-1", date: "2026-02-14", stepId: "s-1", batchId: "", goodQty: 1, defectQty: 0, operatorName: "Admin", note: "Confirmed spec 5,000 units at 37 THB/unit", cumulativeTotal: 1, createdAt: "2026-02-14" },
          { id: "r-2", date: "2026-02-14", stepId: "s-1", batchId: "", goodQty: 0, defectQty: 0, operatorName: "System", note: "FDA checked - Active until 2028", cumulativeTotal: 1, createdAt: "2026-02-14" },
        ],
      },
      {
        id: "s-2", stepNumber: 2, name: "Prepare Raw Materials", description: "Stock check, PO, Reserve Lot",
        status: "done", targetQty: 1, completedQty: 1, goodQty: 1, defectQty: 0, unit: "set",
        startDate: "2026-02-15", endDate: "2026-02-16",
        dailyRecords: [
          { id: "r-3", date: "2026-02-15", stepId: "s-2", batchId: "", goodQty: 0, defectQty: 0, operatorName: "System", note: "Stock Check - 2 items shortage: Niacinamide -3.4kg, Bottle -1,500", cumulativeTotal: 0, createdAt: "2026-02-15" },
          { id: "r-4", date: "2026-02-15", stepId: "s-2", batchId: "", goodQty: 0, defectQty: 0, operatorName: "Admin", note: "PO-2602-001 Niacinamide - Thai Chemical", cumulativeTotal: 0, createdAt: "2026-02-15" },
          { id: "r-5", date: "2026-02-15", stepId: "s-2", batchId: "", goodQty: 0, defectQty: 0, operatorName: "Admin", note: "PO-2602-002 Airless Bottle", cumulativeTotal: 0, createdAt: "2026-02-15" },
          { id: "r-6", date: "2026-02-16", stepId: "s-2", batchId: "", goodQty: 1, defectQty: 0, operatorName: "System", note: "All RM received - Reserved RES-2026-0601", cumulativeTotal: 1, createdAt: "2026-02-16" },
        ],
      },
      {
        id: "s-3", stepNumber: 3, name: "Mixing / Compounding", description: "Mix Phase A + B + Active - 2 Batches",
        status: "done", targetQty: 150, completedQty: 150, goodQty: 150, defectQty: 0, unit: "kg",
        startDate: "2026-02-17", endDate: "2026-02-18",
        dailyRecords: [
          { id: "r-7", date: "2026-02-17", stepId: "s-3", batchId: "b-1", goodQty: 75, defectQty: 0, operatorName: "K. Somsri", note: "Mixing Phase A (Water Phase) - heat to 75C", cumulativeTotal: 75, createdAt: "2026-02-17" },
          { id: "r-8", date: "2026-02-17", stepId: "s-3", batchId: "b-1", goodQty: 75, defectQty: 0, operatorName: "K. Somsri", note: "Mixing Phase B (Oil Phase) + Add Active", cumulativeTotal: 150, createdAt: "2026-02-17" },
          { id: "r-9", date: "2026-02-18", stepId: "s-3", batchId: "b-2", goodQty: 75, defectQty: 0, operatorName: "K. Somsri", note: "Mixing Batch 2 - Phase A + B", cumulativeTotal: 150, createdAt: "2026-02-18" },
        ],
      },
      {
        id: "s-4", stepNumber: 4, name: "Filling", description: "Fill 30ml into Airless Pump bottles - Target 5,000 units",
        status: "active", targetQty: 5000, completedQty: 3200, goodQty: 3180, defectQty: 20, unit: "pcs",
        startDate: "2026-02-18", endDate: null,
        dailyRecords: [
          { id: "r-10", date: "2026-02-21", stepId: "s-4", batchId: "b-3", goodQty: 500, defectQty: 0, operatorName: "K. Somsri", note: "Morning shift", cumulativeTotal: 3200, createdAt: "2026-02-21" },
          { id: "r-11", date: "2026-02-20", stepId: "s-4", batchId: "b-2", goodQty: 700, defectQty: 5, operatorName: "K. Wichai", note: "Afternoon shift - weight within spec", cumulativeTotal: 2700, createdAt: "2026-02-20" },
          { id: "r-12", date: "2026-02-20", stepId: "s-4", batchId: "b-2", goodQty: 500, defectQty: 3, operatorName: "K. Somsri", note: "Morning shift", cumulativeTotal: 2000, createdAt: "2026-02-20" },
          { id: "r-13", date: "2026-02-19", stepId: "s-4", batchId: "b-1", goodQty: 800, defectQty: 7, operatorName: "K. Wichai", note: "Batch A almost complete", cumulativeTotal: 1500, createdAt: "2026-02-19" },
          { id: "r-14", date: "2026-02-18", stepId: "s-4", batchId: "b-1", goodQty: 700, defectQty: 5, operatorName: "K. Somsri", note: "Start filling Batch A", cumulativeTotal: 700, createdAt: "2026-02-18" },
        ],
      },
      {
        id: "s-5", stepNumber: 5, name: "QC / Quality Check", description: "pH, Viscosity, Microbial, Appearance, COA",
        status: "pending", targetQty: 5000, completedQty: 0, goodQty: 0, defectQty: 0, unit: "pcs",
        startDate: null, endDate: null, dailyRecords: [],
      },
      {
        id: "s-6", stepNumber: 6, name: "Labeling", description: "Label GlowUp, Lot/Exp, Barcode",
        status: "pending", targetQty: 5000, completedQty: 0, goodQty: 0, defectQty: 0, unit: "pcs",
        startDate: null, endDate: null, dailyRecords: [],
      },
      {
        id: "s-7", stepNumber: 7, name: "Packing", description: "Art Paper box 350g, Shrink Wrap, Sticker",
        status: "pending", targetQty: 5000, completedQty: 0, goodQty: 0, defectQty: 0, unit: "pcs",
        startDate: null, endDate: null, dailyRecords: [],
      },
      {
        id: "s-8", stepNumber: 8, name: "Delivery", description: "Ship to Glow Lab warehouse - Bangkok",
        status: "pending", targetQty: 1, completedQty: 0, goodQty: 0, defectQty: 0, unit: "shipment",
        startDate: null, endDate: null, dailyRecords: [],
      },
    ],
    materials: [
      { id: "m-1", name: "Ethyl Ascorbic Acid", requiredQty: 22.5, requiredUnit: "kg", lot: "LOT-2501-A", stockQty: 28.0, status: "sufficient", reservedQty: 22.5 },
      { id: "m-2", name: "Niacinamide", requiredQty: 7.5, requiredUnit: "kg", lot: "LOT-2602-D", stockQty: 7.5, status: "ordered", reservedQty: 7.5 },
      { id: "m-3", name: "Sodium Hyaluronate", requiredQty: 1.5, requiredUnit: "kg", lot: "LOT-2502-B", stockQty: 2.3, status: "sufficient", reservedQty: 1.5 },
      { id: "m-4", name: "Airless Bottle 30ml", requiredQty: 5000, requiredUnit: "pcs", lot: "LOT-PKG-0221", stockQty: 5000, status: "ordered", reservedQty: 5000 },
    ],
    qcResults: [
      { id: "qc-1", parameter: "pH", specification: "5.5 - 6.5", result: "6.1", status: "pass", tester: "Dr. Somchai" },
      { id: "qc-2", parameter: "Viscosity", specification: "1000 - 3000 cPs", result: "2,450 cPs", status: "pass", tester: "Dr. Somchai" },
      { id: "qc-3", parameter: "Microbial (TPC)", specification: "< 100 CFU/g", result: "< 10 CFU/g", status: "pass", tester: "Lab Team" },
      { id: "qc-4", parameter: "Appearance", specification: "Clear, Pale Yellow", result: "Clear, Pale Yellow", status: "pass", tester: "Dr. Somchai" },
    ],
    costBreakdown: { rawMaterial: 92500, packaging: 31000, labor: 10000, qcOverhead: 6500, total: 140000 },
    yieldAnalysis: { totalInput: 150, totalOutput: 147.75, yieldLoss: 2.25, yieldLossPercent: 1.5, unit: "kg" },
  },
  {
    id: "jo-2",
    orderNumber: "CZ-2602",
    customerId: "c-2",
    customerName: "BeautyKing",
    brandName: "K-Glow",
    productName: "Hyaluronic Acid Toner",
    sku: "SKU-HA-150",
    formulaCode: "FM-HA01-R2",
    fdaRegNumber: "10-1-67-00456",
    fdaStatus: "active",
    quantity: 8000,
    unitSize: "150ml",
    batchSize: 4000,
    numberOfBatches: 2,
    status: "preparing_rm",
    priority: "medium",
    totalValue: 280000,
    costPerUnit: 22,
    sellingPricePerUnit: 35,
    paymentTerms: "Net 30",
    dueDate: "2026-03-15",
    startDate: "2026-02-20",
    notes: "",
    createdAt: "2026-02-20",
    updatedAt: "2026-02-21",
    batches: [
      { id: "b-4", batchNumber: "#B-2602A", quantity: 4000, status: "producing", completedDate: null },
      { id: "b-5", batchNumber: "#B-2602B", quantity: 4000, status: "producing", completedDate: null },
    ],
    productionSteps: [
      { id: "s-21", stepNumber: 1, name: "Receive Order", description: "Confirm specs", status: "done", targetQty: 1, completedQty: 1, goodQty: 1, defectQty: 0, unit: "order", startDate: "2026-02-20", endDate: "2026-02-20", dailyRecords: [] },
      { id: "s-22", stepNumber: 2, name: "Prepare Raw Materials", description: "Stock check, PO", status: "active", targetQty: 1, completedQty: 0, goodQty: 0, defectQty: 0, unit: "set", startDate: "2026-02-21", endDate: null, dailyRecords: [] },
      { id: "s-23", stepNumber: 3, name: "Mixing", description: "Mix formula", status: "pending", targetQty: 1200, completedQty: 0, goodQty: 0, defectQty: 0, unit: "kg", startDate: null, endDate: null, dailyRecords: [] },
      { id: "s-24", stepNumber: 4, name: "Filling", description: "Fill 150ml bottles", status: "pending", targetQty: 8000, completedQty: 0, goodQty: 0, defectQty: 0, unit: "pcs", startDate: null, endDate: null, dailyRecords: [] },
      { id: "s-25", stepNumber: 5, name: "QC", description: "Quality check", status: "pending", targetQty: 8000, completedQty: 0, goodQty: 0, defectQty: 0, unit: "pcs", startDate: null, endDate: null, dailyRecords: [] },
      { id: "s-26", stepNumber: 6, name: "Packing", description: "Pack into boxes", status: "pending", targetQty: 8000, completedQty: 0, goodQty: 0, defectQty: 0, unit: "pcs", startDate: null, endDate: null, dailyRecords: [] },
      { id: "s-27", stepNumber: 7, name: "Delivery", description: "Ship to BeautyKing", status: "pending", targetQty: 1, completedQty: 0, goodQty: 0, defectQty: 0, unit: "shipment", startDate: null, endDate: null, dailyRecords: [] },
    ],
    materials: [
      { id: "m-5", name: "Sodium Hyaluronate", requiredQty: 12, requiredUnit: "kg", lot: "LOT-2502-B", stockQty: 2.3, status: "shortage", reservedQty: 0 },
      { id: "m-6", name: "Glycerin", requiredQty: 80, requiredUnit: "kg", lot: "LOT-GL-0115", stockQty: 120, status: "sufficient", reservedQty: 80 },
    ],
    qcResults: [],
    costBreakdown: { rawMaterial: 100000, packaging: 32000, labor: 16000, qcOverhead: 8000, total: 156000 },
    yieldAnalysis: { totalInput: 0, totalOutput: 0, yieldLoss: 0, yieldLossPercent: 0, unit: "kg" },
  },
  {
    id: "jo-3",
    orderNumber: "CZ-2600",
    customerId: "c-3",
    customerName: "PureMind",
    brandName: "ClearSkin",
    productName: "Cleansing Foam pH 5.5",
    sku: "SKU-CF55-150",
    formulaCode: "FM-CF55-R1",
    fdaRegNumber: "10-1-67-00789",
    fdaStatus: "active",
    quantity: 15000,
    unitSize: "150ml",
    batchSize: 5000,
    numberOfBatches: 3,
    status: "qc",
    priority: "medium",
    totalValue: 375000,
    costPerUnit: 15,
    sellingPricePerUnit: 25,
    paymentTerms: "Net 45",
    dueDate: "2026-03-10",
    startDate: "2026-02-01",
    notes: "",
    createdAt: "2026-02-01",
    updatedAt: "2026-02-20",
    batches: [],
    productionSteps: [
      { id: "s-31", stepNumber: 1, name: "Receive Order", description: "Confirm", status: "done", targetQty: 1, completedQty: 1, goodQty: 1, defectQty: 0, unit: "order", startDate: "2026-02-01", endDate: "2026-02-01", dailyRecords: [] },
      { id: "s-32", stepNumber: 2, name: "Prepare RM", description: "Stock check", status: "done", targetQty: 1, completedQty: 1, goodQty: 1, defectQty: 0, unit: "set", startDate: "2026-02-02", endDate: "2026-02-04", dailyRecords: [] },
      { id: "s-33", stepNumber: 3, name: "Mixing", description: "Mix foam formula", status: "done", targetQty: 2250, completedQty: 2250, goodQty: 2250, defectQty: 0, unit: "kg", startDate: "2026-02-05", endDate: "2026-02-10", dailyRecords: [] },
      { id: "s-34", stepNumber: 4, name: "Filling", description: "Fill 150ml tubes", status: "done", targetQty: 15000, completedQty: 15000, goodQty: 14880, defectQty: 120, unit: "pcs", startDate: "2026-02-11", endDate: "2026-02-18", dailyRecords: [] },
      { id: "s-35", stepNumber: 5, name: "QC", description: "Quality inspection", status: "active", targetQty: 15000, completedQty: 12000, goodQty: 11900, defectQty: 100, unit: "pcs", startDate: "2026-02-19", endDate: null, dailyRecords: [] },
      { id: "s-36", stepNumber: 6, name: "Packing", description: "Pack and shrink wrap", status: "pending", targetQty: 15000, completedQty: 0, goodQty: 0, defectQty: 0, unit: "pcs", startDate: null, endDate: null, dailyRecords: [] },
      { id: "s-37", stepNumber: 7, name: "Delivery", description: "Ship to PureMind", status: "pending", targetQty: 1, completedQty: 0, goodQty: 0, defectQty: 0, unit: "shipment", startDate: null, endDate: null, dailyRecords: [] },
    ],
    materials: [],
    qcResults: [],
    costBreakdown: { rawMaterial: 120000, packaging: 50000, labor: 25000, qcOverhead: 15000, total: 210000 },
    yieldAnalysis: { totalInput: 2250, totalOutput: 2220, yieldLoss: 30, yieldLossPercent: 1.33, unit: "kg" },
  },
  {
    id: "jo-4",
    orderNumber: "CZ-2599",
    customerId: "c-4",
    customerName: "LuxeSkin",
    brandName: "LuxeGlow",
    productName: "Sleeping Mask Lavender",
    sku: "SKU-SM-50",
    formulaCode: "FM-SML-R2",
    fdaRegNumber: "10-1-67-00321",
    fdaStatus: "active",
    quantity: 3000,
    unitSize: "50ml",
    batchSize: 3000,
    numberOfBatches: 1,
    status: "delivered",
    priority: "low",
    totalValue: 120000,
    costPerUnit: 25,
    sellingPricePerUnit: 40,
    paymentTerms: "Net 30",
    dueDate: "2026-02-18",
    startDate: "2026-01-20",
    notes: "",
    createdAt: "2026-01-20",
    updatedAt: "2026-02-18",
    batches: [],
    productionSteps: [
      { id: "s-41", stepNumber: 1, name: "Receive Order", description: "", status: "done", targetQty: 1, completedQty: 1, goodQty: 1, defectQty: 0, unit: "order", startDate: "2026-01-20", endDate: "2026-01-20", dailyRecords: [] },
      { id: "s-42", stepNumber: 2, name: "Prepare RM", description: "", status: "done", targetQty: 1, completedQty: 1, goodQty: 1, defectQty: 0, unit: "set", startDate: "2026-01-21", endDate: "2026-01-23", dailyRecords: [] },
      { id: "s-43", stepNumber: 3, name: "Mixing", description: "", status: "done", targetQty: 150, completedQty: 150, goodQty: 150, defectQty: 0, unit: "kg", startDate: "2026-01-24", endDate: "2026-01-26", dailyRecords: [] },
      { id: "s-44", stepNumber: 4, name: "Filling", description: "", status: "done", targetQty: 3000, completedQty: 3000, goodQty: 2980, defectQty: 20, unit: "pcs", startDate: "2026-01-27", endDate: "2026-02-02", dailyRecords: [] },
      { id: "s-45", stepNumber: 5, name: "QC", description: "", status: "done", targetQty: 3000, completedQty: 3000, goodQty: 2980, defectQty: 20, unit: "pcs", startDate: "2026-02-03", endDate: "2026-02-05", dailyRecords: [] },
      { id: "s-46", stepNumber: 6, name: "Packing", description: "", status: "done", targetQty: 3000, completedQty: 3000, goodQty: 2980, defectQty: 0, unit: "pcs", startDate: "2026-02-06", endDate: "2026-02-10", dailyRecords: [] },
      { id: "s-47", stepNumber: 7, name: "Delivery", description: "", status: "done", targetQty: 1, completedQty: 1, goodQty: 1, defectQty: 0, unit: "shipment", startDate: "2026-02-18", endDate: "2026-02-18", dailyRecords: [] },
    ],
    materials: [],
    qcResults: [],
    costBreakdown: { rawMaterial: 42000, packaging: 18000, labor: 6000, qcOverhead: 4000, total: 70000 },
    yieldAnalysis: { totalInput: 150, totalOutput: 149, yieldLoss: 1, yieldLossPercent: 0.67, unit: "kg" },
  },
  {
    id: "jo-5",
    orderNumber: "CZ-2603",
    customerId: "c-5",
    customerName: "NaturaSkin",
    brandName: "NaturaGlow",
    productName: "Niacinamide Body Lotion",
    sku: "SKU-NBL-250",
    formulaCode: "FM-NBL-R1",
    fdaRegNumber: "10-1-68-00012",
    fdaStatus: "active",
    quantity: 10000,
    unitSize: "250ml",
    batchSize: 5000,
    numberOfBatches: 2,
    status: "new",
    priority: "low",
    totalValue: 350000,
    costPerUnit: 20,
    sellingPricePerUnit: 35,
    paymentTerms: "Net 30",
    dueDate: "2026-03-25",
    startDate: "2026-02-22",
    notes: "",
    createdAt: "2026-02-22",
    updatedAt: "2026-02-22",
    batches: [],
    productionSteps: [
      { id: "s-51", stepNumber: 1, name: "Receive Order", description: "Confirm specs", status: "active", targetQty: 1, completedQty: 0, goodQty: 0, defectQty: 0, unit: "order", startDate: null, endDate: null, dailyRecords: [] },
      { id: "s-52", stepNumber: 2, name: "Prepare RM", description: "Stock check", status: "pending", targetQty: 1, completedQty: 0, goodQty: 0, defectQty: 0, unit: "set", startDate: null, endDate: null, dailyRecords: [] },
      { id: "s-53", stepNumber: 3, name: "Mixing", description: "Mix formula", status: "pending", targetQty: 2500, completedQty: 0, goodQty: 0, defectQty: 0, unit: "kg", startDate: null, endDate: null, dailyRecords: [] },
      { id: "s-54", stepNumber: 4, name: "Filling", description: "Fill 250ml bottles", status: "pending", targetQty: 10000, completedQty: 0, goodQty: 0, defectQty: 0, unit: "pcs", startDate: null, endDate: null, dailyRecords: [] },
      { id: "s-55", stepNumber: 5, name: "QC", description: "Quality check", status: "pending", targetQty: 10000, completedQty: 0, goodQty: 0, defectQty: 0, unit: "pcs", startDate: null, endDate: null, dailyRecords: [] },
      { id: "s-56", stepNumber: 6, name: "Packing", description: "Pack", status: "pending", targetQty: 10000, completedQty: 0, goodQty: 0, defectQty: 0, unit: "pcs", startDate: null, endDate: null, dailyRecords: [] },
      { id: "s-57", stepNumber: 7, name: "Delivery", description: "Ship to NaturaSkin", status: "pending", targetQty: 1, completedQty: 0, goodQty: 0, defectQty: 0, unit: "shipment", startDate: null, endDate: null, dailyRecords: [] },
    ],
    materials: [],
    qcResults: [],
    costBreakdown: { rawMaterial: 110000, packaging: 40000, labor: 20000, qcOverhead: 10000, total: 180000 },
    yieldAnalysis: { totalInput: 0, totalOutput: 0, yieldLoss: 0, yieldLossPercent: 0, unit: "kg" },
  },
]
