import type { ProductListItem, ProductKPISummary, Product, ProductLot, AuditEntry } from "./product-types"

export const mockKPI: ProductKPISummary = {
  total: 248,
  active: 186,
  inDevelopment: 32,
  fdaWarning: 12,
  discontinued: 18,
}

export const mockProducts: ProductListItem[] = [
  {
    id: "1",
    sku: "SKU-VC15-30",
    nameInternal: "Vitamin C Brightening Serum",
    thumbnailUrl: undefined,
    customerName: "Glow Lab Co., Ltd.",
    brandName: "GlowUp",
    category: "skincare",
    sellingPrice: 185,
    totalCostPerUnit: 21.63,
    marginPercent: 88.3,
    fdaStatus: "approved",
    status: "active",
    packageSize: "30 ml",
    containerType: "dropper",
  },
  {
    id: "2",
    sku: "SKU-UV50-50",
    nameInternal: "UV Shield Sunscreen SPF50",
    thumbnailUrl: undefined,
    customerName: "Glow Lab Co., Ltd.",
    brandName: "GlowUp",
    category: "suncare",
    sellingPrice: 250,
    totalCostPerUnit: 35.20,
    marginPercent: 85.9,
    fdaStatus: "approved",
    status: "active",
    packageSize: "50 ml",
    containerType: "tube",
  },
  {
    id: "3",
    sku: "SKU-HA-30",
    nameInternal: "Hyaluronic Acid Moisture Serum",
    thumbnailUrl: undefined,
    customerName: "NatuGlow Inc.",
    brandName: "NatuGlow",
    category: "skincare",
    sellingPrice: 220,
    totalCostPerUnit: 28.50,
    marginPercent: 87.0,
    fdaStatus: "pending",
    status: "in_development",
    packageSize: "30 ml",
    containerType: "airless_pump",
  },
  {
    id: "4",
    sku: "SKU-CL-150",
    nameInternal: "Gentle Foam Cleanser",
    thumbnailUrl: undefined,
    customerName: "SoftTouch Beauty",
    brandName: "SoftTouch",
    category: "cleanser",
    sellingPrice: 150,
    totalCostPerUnit: 18.40,
    marginPercent: 87.7,
    fdaStatus: "approved",
    status: "active",
    packageSize: "150 ml",
    containerType: "pump_bottle",
  },
  {
    id: "5",
    sku: "SKU-BL-200",
    nameInternal: "Body Whitening Lotion",
    thumbnailUrl: undefined,
    customerName: "SoftTouch Beauty",
    brandName: "SoftTouch",
    category: "bodycare",
    sellingPrice: 180,
    totalCostPerUnit: 22.10,
    marginPercent: 87.7,
    fdaStatus: "approved",
    status: "active",
    packageSize: "200 ml",
    containerType: "pump_bottle",
  },
  {
    id: "6",
    sku: "SKU-RT-30",
    nameInternal: "Retinol Anti-Aging Cream",
    thumbnailUrl: undefined,
    customerName: "NatuGlow Inc.",
    brandName: "NatuGlow",
    category: "skincare",
    sellingPrice: 350,
    totalCostPerUnit: 45.80,
    marginPercent: 86.9,
    fdaStatus: "expired",
    status: "active",
    packageSize: "30 g",
    containerType: "jar",
  },
  {
    id: "7",
    sku: "SKU-HP-250",
    nameInternal: "Keratin Hair Treatment",
    thumbnailUrl: undefined,
    customerName: "Hair Plus Co.",
    brandName: "HairPlus",
    category: "haircare",
    sellingPrice: 280,
    totalCostPerUnit: 32.50,
    marginPercent: 88.4,
    fdaStatus: "approved",
    status: "active",
    packageSize: "250 ml",
    containerType: "bottle",
  },
  {
    id: "8",
    sku: "SKU-COL-50",
    nameInternal: "Collagen Drink Supplement",
    thumbnailUrl: undefined,
    customerName: "Glow Lab Co., Ltd.",
    brandName: "GlowUp",
    category: "supplement",
    sellingPrice: 45,
    totalCostPerUnit: 8.20,
    marginPercent: 81.8,
    fdaStatus: "approved",
    status: "active",
    packageSize: "50 ml",
    containerType: "bottle",
  },
  {
    id: "9",
    sku: "SKU-NR-15",
    nameInternal: "Niacinamide Radiance Serum",
    thumbnailUrl: undefined,
    customerName: "Glow Lab Co., Ltd.",
    brandName: "GlowUp",
    category: "skincare",
    sellingPrice: undefined,
    totalCostPerUnit: 19.50,
    marginPercent: 0,
    fdaStatus: "not_registered",
    status: "draft",
    packageSize: "15 ml",
    containerType: "dropper",
  },
  {
    id: "10",
    sku: "SKU-LM-30",
    nameInternal: "Lip Matte Mousse",
    thumbnailUrl: undefined,
    customerName: "SoftTouch Beauty",
    brandName: "SoftTouch",
    category: "makeup",
    sellingPrice: 120,
    totalCostPerUnit: 15.80,
    marginPercent: 86.8,
    fdaStatus: "approved",
    status: "discontinued",
    packageSize: "5 g",
    containerType: "tube",
  },
]

export const mockProductDetail: Product = {
  id: "1",
  sku: "SKU-VC15-30",
  barcode: "8851234567890",
  nameInternal: "Vitamin C Brightening Serum",
  nameTH: "เซรั่มวิตามินซี ไบรท์เทนนิ่ง",
  nameEN: "Vitamin C Brightening Serum",
  tradeName_TH: "กลาวอัพ วิตามินซี เซรั่ม",
  tradeName_EN: "GlowUp Vitamin C Serum",
  description: "เซรั่มเข้มข้นผสานวิตามินซี 15% ช่วยลดเลือนจุดด่างดำ ผิวกระจ่างใสอย่างเป็นธรรมชาติ",
  category: "skincare",
  customerId: "cust-001",
  customerName: "Glow Lab Co., Ltd.",
  brandId: "brand-001",
  brandName: "GlowUp",
  formulaId: "fml-001",
  formulaCode: "FML-HYASERUM-001",
  formulaName: "Hyaluronic Serum Formula",
  fdaLicenseId: "fda-001",
  fdaLicenseNumber: "10-1-12345-5-0001",
  fillWeight: 30,
  fillWeightUnit: "ml",
  shelfLifeMonths: 24,
  paoMonths: 12,
  storageCondition: "Store below 30C",
  containerType: "dropper",
  containerMaterial: "Glass",
  containerShape: "Cylinder",
  capType: "Dropper",
  packageSize: "30 ml",
  qcSpec: {
    appearance: "Clear light yellow liquid, free from foreign matters",
    color: "Light Yellow",
    scent: "Citrus",
    texture: "Liquid Serum",
    phMin: 5.5,
    phMax: 6.5,
    viscosityMin: 300,
    viscosityMax: 500,
    specificGravityMin: 0.9,
    specificGravityMax: 1.1,
  },
  bulkCostPerUnit: 1.28,
  packagingCostPerUnit: 17.05,
  laborCostPerUnit: 2.0,
  overheadCostPerUnit: 1.3,
  totalCostPerUnit: 21.63,
  sellingPrice: 185,
  moq: 1000,
  leadTimeDays: 30,
  status: "active",
  fdaStatus: "approved",
  bomItems: [
    { id: "bom-1", type: "bottle", stockItemId: "stk-1", stockItemName: "Dropper Bottle 30ml Frosted", stockItemCode: "PKG-BT-30DF", quantity: 1, wastePercent: 2, unitCost: 8.50, effectiveCost: 8.67 },
    { id: "bom-2", type: "pump", stockItemId: "stk-2", stockItemName: "Dropper Pump Gold 18mm", stockItemCode: "PKG-PM-18G", quantity: 1, wastePercent: 1, unitCost: 3.20, effectiveCost: 3.23 },
    { id: "bom-3", type: "sticker", stockItemId: "stk-3", stockItemName: "Label Sticker GlowUp Serum", stockItemCode: "PKG-LB-GWSR", quantity: 1, conversionQty: 7000, conversionUnit: "roll", wastePercent: 3, unitCost: 500, effectiveCost: 0.074 },
    { id: "bom-4", type: "box", stockItemId: "stk-4", stockItemName: "Individual Box Serum 30ml", stockItemCode: "PKG-BX-30SR", quantity: 1, wastePercent: 1.5, unitCost: 5.00, effectiveCost: 5.08 },
  ],
  pricingTiers: [
    { id: "tier-1", minQty: 1000, maxQty: 2999, pricePerUnit: 185, grossMarginPercent: 88.3, profitPerUnit: 163.37 },
    { id: "tier-2", minQty: 3000, maxQty: 4999, pricePerUnit: 165, grossMarginPercent: 86.9, profitPerUnit: 143.37 },
    { id: "tier-3", minQty: 5000, maxQty: 9999, pricePerUnit: 150, grossMarginPercent: 85.6, profitPerUnit: 128.37 },
    { id: "tier-4", minQty: 10000, pricePerUnit: 135, grossMarginPercent: 84.0, profitPerUnit: 113.37 },
  ],
  images: [],
  attachments: [
    { id: "att-1", fileName: "COA-VC15-Lot240601.pdf", fileUrl: "#", fileSize: "2.4 MB", fileType: "Certificate", uploadedAt: "2026-01-15" },
    { id: "att-2", fileName: "Stability-Report-6M.pdf", fileUrl: "#", fileSize: "5.1 MB", fileType: "Test Report", uploadedAt: "2026-01-10" },
    { id: "att-3", fileName: "Product-Spec-VC15.pdf", fileUrl: "#", fileSize: "1.2 MB", fileType: "Spec Sheet", uploadedAt: "2025-12-20" },
  ],
  totalProduced: 45000,
  inStockQty: 12500,
  lotCount: 5,
  createdAt: "2025-06-15",
  updatedAt: "2026-02-28",
  createdBy: "Admin",
}

export const mockLots: ProductLot[] = [
  {
    id: "lot-1",
    productId: "1",
    lotNumber: "LOT-260201",
    jobOrderId: "jo-101",
    jobOrderNumber: "JO-2026-0101",
    mfgDate: "2026-02-01",
    expDate: "2028-02-01",
    daysUntilExpiry: 700,
    quantity: 10000,
    yieldPercent: 98.2,
    qcResult: "pass",
    qcData: { appearance: "Clear yellow liquid", odor: "Normal citrus", phValue: 5.8, viscosity: 420, specificGravity: 1.02, microTest: "< 100 CFU/g" },
    inStockQty: 8500,
    deliveredQty: 1500,
    costPerUnit: 21.63,
    status: "released",
    coaUrl: "#",
    deliveries: [
      { id: "d-1", date: "2026-02-10", customerName: "Glow Lab Co., Ltd.", invoiceNumber: "INV-2026-0032", quantity: 1000, courier: "Kerry" },
      { id: "d-2", date: "2026-02-20", customerName: "Glow Lab Co., Ltd.", invoiceNumber: "INV-2026-0045", quantity: 500, courier: "Flash" },
    ],
    createdAt: "2026-02-01",
    createdBy: "Admin",
  },
  {
    id: "lot-2",
    productId: "1",
    lotNumber: "LOT-260115",
    jobOrderId: "jo-095",
    jobOrderNumber: "JO-2026-0095",
    mfgDate: "2026-01-15",
    expDate: "2028-01-15",
    daysUntilExpiry: 683,
    quantity: 15000,
    yieldPercent: 97.5,
    qcResult: "pass",
    qcData: { appearance: "Clear yellow liquid", odor: "Normal", phValue: 5.6, viscosity: 410, specificGravity: 1.01, microTest: "< 100 CFU/g" },
    inStockQty: 4000,
    deliveredQty: 11000,
    costPerUnit: 21.63,
    status: "released",
    coaUrl: "#",
    deliveries: [
      { id: "d-3", date: "2026-01-25", customerName: "Glow Lab Co., Ltd.", invoiceNumber: "INV-2026-0018", quantity: 5000, courier: "Kerry" },
      { id: "d-4", date: "2026-02-05", customerName: "Glow Lab Co., Ltd.", invoiceNumber: "INV-2026-0028", quantity: 6000, courier: "Kerry" },
    ],
    createdAt: "2026-01-15",
    createdBy: "Admin",
  },
  {
    id: "lot-3",
    productId: "1",
    lotNumber: "LOT-251201",
    jobOrderId: "jo-082",
    jobOrderNumber: "JO-2025-0082",
    mfgDate: "2025-12-01",
    expDate: "2027-12-01",
    quantity: 10000,
    yieldPercent: 96.8,
    qcResult: "pass",
    qcData: { appearance: "Clear yellow liquid", odor: "Normal", phValue: 6.0, viscosity: 430 },
    inStockQty: 0,
    deliveredQty: 10000,
    costPerUnit: 22.10,
    status: "sold_out",
    deliveries: [],
    createdAt: "2025-12-01",
    createdBy: "Admin",
  },
  {
    id: "lot-4",
    productId: "1",
    lotNumber: "LOT-251101",
    mfgDate: "2025-11-01",
    expDate: "2027-11-01",
    quantity: 5000,
    yieldPercent: 94.2,
    qcResult: "fail",
    qcData: { appearance: "Slightly cloudy", odor: "Off-odor detected", phValue: 4.8, viscosity: 250 },
    inStockQty: 0,
    deliveredQty: 0,
    costPerUnit: 21.63,
    status: "rejected",
    deliveries: [],
    remark: "pH out of spec, viscosity below range",
    createdAt: "2025-11-01",
    createdBy: "Admin",
  },
  {
    id: "lot-5",
    productId: "1",
    lotNumber: "LOT-260228",
    mfgDate: "2026-02-28",
    expDate: "2028-02-28",
    quantity: 8000,
    qcResult: "pending",
    qcData: {},
    inStockQty: 0,
    deliveredQty: 0,
    costPerUnit: 21.63,
    status: "qc_hold",
    deliveries: [],
    remark: "Awaiting QC testing",
    createdAt: "2026-02-28",
    createdBy: "Admin",
  },
]

export const mockAudit: AuditEntry[] = [
  { id: "a-1", action: "created", description: "Product created", userName: "Admin", timestamp: "2025-06-15 10:30", color: "blue" },
  { id: "a-2", action: "updated", description: "Added BOM components", userName: "Admin", timestamp: "2025-06-16 14:20", color: "blue" },
  { id: "a-3", action: "formula_linked", description: "Linked formula FML-HYASERUM-001", userName: "Admin", timestamp: "2025-06-20 09:15", color: "purple" },
  { id: "a-4", action: "price_updated", description: "Selling price updated to 185 THB", userName: "Admin", timestamp: "2025-08-10 11:00", color: "green" },
  { id: "a-5", action: "lot_created", description: "Lot LOT-251201 created (10,000 units)", userName: "Admin", timestamp: "2025-12-01 08:00", color: "orange" },
  { id: "a-6", action: "lot_created", description: "Lot LOT-260115 created (15,000 units)", userName: "Admin", timestamp: "2026-01-15 08:00", color: "orange" },
  { id: "a-7", action: "lot_created", description: "Lot LOT-260201 created (10,000 units)", userName: "Admin", timestamp: "2026-02-01 08:00", color: "orange" },
  { id: "a-8", action: "updated", description: "QC Spec updated - appearance standard", userName: "Admin", timestamp: "2026-02-15 16:45", color: "blue" },
]
