import type { SupplierListItem, SupplierDetail, SupplierKPI } from "./supplier-types"

export const mockSupplierKPI: SupplierKPI = {
  totalSuppliers: 18,
  activeSuppliers: 14,
  approvedSuppliers: 12,
  pendingApproval: 2,
  avgRating: 4.2,
}

export const mockSupplierList: SupplierListItem[] = [
  {
    id: "sup-1",
    supplierCode: "SUP-003",
    supplierName: "Nikko Chemicals Co., Ltd.",
    supplierNameEn: "Nikko Chemicals",
    supplierType: "raw_material",
    country: "Japan",
    city: "Osaka",
    contactPerson: "Tanaka Hiroshi",
    email: "export@nikko-chem.co.jp",
    phone: "+81-6-xxxx-xxxx",
    isActive: true,
    isApproved: true,
    grade: "A+",
    qualityRating: 4.8,
    deliveryRating: 4.5,
    priceRating: 4.0,
    materialTags: [
      { label: "EAA", color: "text-[#4c8bf5]", bg: "bg-[#eef4ff]" },
      { label: "UV Filters", color: "text-[#14b8a6]", bg: "bg-[#ccfbf1]" },
    ],
    status: "active",
  },
  {
    id: "sup-2",
    supplierCode: "SUP-007",
    supplierName: "BASF SE",
    supplierNameEn: "BASF",
    supplierType: "raw_material",
    country: "Germany",
    city: "Ludwigshafen",
    contactPerson: "Hans Mueller",
    email: "care-chem@basf.com",
    phone: "+49-621-xxxx",
    isActive: true,
    isApproved: true,
    grade: "A",
    qualityRating: 4.7,
    deliveryRating: 4.3,
    priceRating: 3.5,
    materialTags: [
      { label: "Emulsifiers", color: "text-[#8b5cf6]", bg: "bg-[#f3efff]" },
      { label: "Thickeners", color: "text-[#f59e0b]", bg: "bg-[#fef3c7]" },
    ],
    status: "active",
  },
  {
    id: "sup-3",
    supplierCode: "SUP-005",
    supplierName: "Bloomage BioTech Corp.",
    supplierNameEn: "Bloomage BioTech",
    supplierType: "raw_material",
    country: "Korea",
    city: "Seoul",
    contactPerson: "Kim Soo-jin",
    email: "export@bloomage.kr",
    phone: "+82-2-xxxx",
    isActive: true,
    isApproved: true,
    grade: "A",
    qualityRating: 4.5,
    deliveryRating: 4.0,
    priceRating: 4.2,
    materialTags: [
      { label: "HA", color: "text-[#ec4899]", bg: "bg-[#fdf2f8]" },
      { label: "Ceramide", color: "text-[#f59e0b]", bg: "bg-[#fef3c7]" },
    ],
    status: "active",
  },
  {
    id: "sup-4",
    supplierCode: "SUP-001",
    supplierName: "ThaiOL Chemical Co., Ltd.",
    supplierType: "raw_material",
    country: "Thailand",
    city: "Bangkok",
    contactPerson: "Somchai K.",
    email: "sales@thaiol.co.th",
    phone: "02-xxx-xxxx",
    isActive: true,
    isApproved: true,
    grade: "A+",
    qualityRating: 4.6,
    deliveryRating: 4.8,
    priceRating: 4.5,
    materialTags: [
      { label: "Glycerin", color: "text-[#10b981]", bg: "bg-[#ecfdf5]" },
      { label: "PG", color: "text-[#4c8bf5]", bg: "bg-[#eef4ff]" },
    ],
    status: "active",
  },
  {
    id: "sup-5",
    supplierCode: "SUP-010",
    supplierName: "Siam Packaging Co., Ltd.",
    supplierType: "packaging",
    country: "Thailand",
    city: "Bangkok",
    contactPerson: "Anchalee P.",
    email: "info@siampkg.co.th",
    phone: "02-xxx-xxxx",
    isActive: true,
    isApproved: true,
    grade: "A",
    qualityRating: 4.3,
    deliveryRating: 4.5,
    priceRating: 4.2,
    materialTags: [
      { label: "Bottles", color: "text-[#8b5cf6]", bg: "bg-[#f3efff]" },
      { label: "Pump", color: "text-[#14b8a6]", bg: "bg-[#ccfbf1]" },
    ],
    status: "active",
  },
  {
    id: "sup-6",
    supplierCode: "SUP-015",
    supplierName: "Shandong Freda Biotech",
    supplierType: "raw_material",
    country: "China",
    city: "Jinan",
    contactPerson: "Wang Li",
    email: "export@freda.cn",
    phone: "+86-531-xxxx",
    isActive: true,
    isApproved: false,
    grade: "C+",
    qualityRating: 3.2,
    deliveryRating: 3.0,
    priceRating: 4.8,
    materialTags: [
      { label: "HA Bulk", color: "text-[#4c8bf5]", bg: "bg-[#eef4ff]" },
      { label: "Niacinamide", color: "text-[#10b981]", bg: "bg-[#ecfdf5]" },
    ],
    status: "issue",
  },
]

// Full detail for Nikko (the default selected)
export const mockSupplierDetail: SupplierDetail = {
  ...mockSupplierList[0],
  description: "Leading Japanese manufacturer of specialty cosmetic ingredients. Known for high-purity EAA and advanced UV filter technology.",
  address: "2-3-7 Hiranomachi, Chuo-ku, Osaka 541-0046, Japan",
  taxId: "JP-1234567890",
  branchCode: "HQ",
  paymentTerms: "T/T 30",
  paymentDays: 30,
  website: "https://nikko-chem.co.jp",
  fax: "+81-6-xxxx-xxxx",
  notes: "Preferred supplier for EAA. Annual contract renewal in March. MOQ varies by product.",
  avgLeadTimeDays: 14,
  ytdOrderValue: 480000,
  moq: "25 kg",
  onTimeDeliveryPct: 98,
  contacts: [
    { id: "c1", contactName: "Tanaka Hiroshi", position: "Export Manager", email: "tanaka@nikko-chem.co.jp", phone: "+81-6-1234-5678", lineId: "tanaka_h", isPrimary: true },
    { id: "c2", contactName: "Yoko Sato", position: "QC Manager", email: "sato@nikko-chem.co.jp", phone: "+81-6-1234-5679", isPrimary: false },
    { id: "c3", contactName: "Kenji Yamamoto", position: "Sales Director", email: "yamamoto@nikko-chem.co.jp", phone: "+81-6-1234-5670", isPrimary: false },
  ],
  addresses: [
    { id: "a1", addressType: "registered", addressName: "Head Office", addressLine1: "2-3-7 Hiranomachi, Chuo-ku, Osaka 541-0046", province: "Osaka", postalCode: "541-0046", isDefault: true },
    { id: "a2", addressType: "warehouse", addressName: "Kobe Warehouse", addressLine1: "1-1 Port Island, Kobe", province: "Hyogo", postalCode: "650-0046", isDefault: false },
  ],
  certificates: [
    { id: "cert1", certificateType: "ISO 22716", certificateName: "ISO 22716:2007 GMP Cosmetics", certificateNumber: "COS-22716-2024", issuingBody: "JQA (Japan Quality Assurance Org.)", issueDate: "2024-03-15", expiryDate: "2027-03-14", status: "active", daysRemaining: 375 },
    { id: "cert2", certificateType: "GMP", certificateName: "GMP Certificate", certificateNumber: "GMP-NK-2024", issuingBody: "MHLW Japan", issueDate: "2024-01-10", expiryDate: "2026-04-10", status: "active", daysRemaining: 38 },
    { id: "cert3", certificateType: "HALAL", certificateName: "HALAL Certification", certificateNumber: "HAL-2024-NK", issuingBody: "Japan Halal Association", issueDate: "2024-06-01", expiryDate: "2025-12-01", status: "expired", daysRemaining: -92 },
  ],
  catalogItems: [
    { id: "cat1", stockItemName: "Ethyl Ascorbic Acid (EAA)", inci: "3-O-Ethyl Ascorbic Acid", unitPrice: 18500, currency: "JPY", leadTimeDays: 14, minOrderQty: 25, unit: "kg", coaStatus: "valid", purity: "99.5%" },
    { id: "cat2", stockItemName: "Uvinul A Plus", inci: "Diethylamino Hydroxybenzoyl Hexyl Benzoate", unitPrice: 12800, currency: "JPY", leadTimeDays: 14, minOrderQty: 50, unit: "kg", coaStatus: "valid", purity: "98%+" },
    { id: "cat3", stockItemName: "Nikkomulese WO-NS", inci: "Polyglyceryl-6 Polyricinoleate", unitPrice: 8200, currency: "JPY", leadTimeDays: 21, minOrderQty: 10, unit: "kg", coaStatus: "valid", purity: "N/A" },
  ],
  documents: [
    { id: "doc1", documentType: "contract", title: "Supply Agreement 2026", fileName: "nikko_supply_agreement_2026.pdf", fileSize: 2400000, createdAt: "2026-01-10" },
    { id: "doc2", documentType: "coa", title: "COA - EAA Lot NK-2602", fileName: "COA_EAA_NK2602.pdf", fileSize: 890000, createdAt: "2026-02-15" },
    { id: "doc3", documentType: "msds", title: "MSDS - Ethyl Ascorbic Acid", fileName: "MSDS_EAA_v3.pdf", fileSize: 1200000, createdAt: "2025-08-20" },
    { id: "doc4", documentType: "specification", title: "Product Spec - Uvinul A Plus", fileName: "spec_uvinul_a_plus.pdf", fileSize: 450000, createdAt: "2025-11-05" },
  ],
  createdAt: "2024-06-15",
  updatedAt: "2026-02-28",
}
